pythonclient: Disconnect also on socket error exception (#840)
* pythonclient: Added debug output EReader thread started

* pythonclient: Disconnect also on socket error exception

PR #837 didn't fix all connection problems.
When the API client tries to re-connect, it happenend that the reader
thread got an exeption from conn.recvMsg() -> _recvAllMsg() -> socket.recv()
   OSError: [Errno 9] Bad file descriptor

Now conn.recvMsg will catch also socket.error and execute disconnect(),
so that EReader and EClient can detect this error.